config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  devise_for :users
  get 'home/index'
  resources :shifts, except: %i[new create] do
    resources :auctions, only: %i[new edit]
  end

  resources :auctions, only: %i[index show update create] do
    resources :bids, only: %i[new edit]
  end

  resources :bids, only: %i[index create update] do
    get 'accept'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  belongs_to :shift
  has_many :bids, dependent: :destroy

  enum status: {
    pending: 0,
    trading: 1,
    closed: 2
  }

  validates :price, numericality: { in: (1...5) }
  accepts_nested_attributes_for :shift

  def bidder
    shift.user
  end

  def date
    "#{shift.start.strftime("%d-%m %H:%M")} a #{shift.end.strftime("%H:%M")}"
  end
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :shift
  belongs_to :bidder, class_name: 'User'

  def bidder
    shift&.user
  end

  def date
    "#{shift.start.strftime("%d-%m %H:%M")} a #{shift.end.strftime("%H:%M")}"
  end
end

app/models/shift.rb
class Shift < ApplicationRecord
  belongs_to :user
  delegate :calendar_id, to: :user
  has_many :auctions, dependent: :destroy
  has_many :bids, dependent: :destroy

  def date
    "#{start.strftime("%d-%m %H:%M")} a #{self.end.strftime("%H:%M")}"
  end

  def self.options_for_select
    options = []
    self.all.each do |shift| 
      options << [shift.date, shift.id]
    end
    options
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shifts, dependent: :destroy
  has_many :auctions, through: :shifts
  has_many :bids, dependent: :destroy, foreign_key: :bidder_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: %i[ show edit update destroy ]

  # GET /auctions or /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1 or /auctions/1.json
  def show
    @bids = @auction.bids
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
    @shift = Shift.find(params[:shift_id])
  end

  # # GET /auctions/1/edit
  # def edit
  # end

  # POST /auctions or /auctions.json
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to auction_url(@auction), notice: "Auction was successfully created." }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /auctions/1 or /auctions/1.json
  # def update
  #   respond_to do |format|
  #     if @auction.update(auction_params)
  #       format.html { redirect_to auction_url(@auction), notice: "Auction was successfully updated." }
  #       format.json { render :show, status: :ok, location: @auction }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @auction.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /auctions/1 or /auctions/1.json
  # def destroy
  #   @auction.destroy

  #   respond_to do |format|
  #     format.html { redirect_to auctions_url, notice: "Auction was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def auction_params
      params.require(:auction).permit(:shift_id, :price, :description, :status, shifts_attributes: [ :id, :start, :end, :user_id ])
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_action :set_bid, only: %i[ show edit update destroy ]

  # GET /bids or /bids.json
  def index
    @bids = current_user.bids
  end

  def accept
    @bid = Bid.find(params[:bid_id])
    @auction = @bid.auction
    shift_1 = @auction.shift
    user_1 = shift_1.user_id
    shift_2 = @bid.shift
    user_2 = shift_2.user_id
    shift_1.update(user_id: user_2)
    shift_2.update(user_id: user_1)
    redirect_to auctions_path, notice: "Cambio realizado"
  end
  # # GET /bids/1 or /bids/1.json
  # def show
  # end

  # GET auctions/:id/bids/new
  def new
    @shifts = current_user.shifts.options_for_select
    @auction = Auction.find(params[:auction_id])
    @bid = @auction.bids.build
  end

  # # GET /bids/1/edit
  # def edit
  # end

  # POST /bids or /bids.json
  def create
    @bid =  Bid.new(bid_params)
    @bid.bidder_id = current_user.id

    respond_to do |format|
      if @bid.save
        format.html { redirect_to bid_url(@bid), notice: "Bid was successfully created." }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /bids/1 or /bids/1.json
  # def update
  #   respond_to do |format|
  #     if @bid.update(bid_params)
  #       format.html { redirect_to bid_url(@bid), notice: "Bid was successfully updated." }
  #       format.json { render :show, status: :ok, location: @bid }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @bid.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /bids/1 or /bids/1.json
  # def destroy
  #   @bid.destroy

  #   respond_to do |format|
  #     format.html { redirect_to bids_url, notice: "Bid was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bid
      @bid = Bid.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bid_params
      params.require(:bid).permit(:auction_id, :shift_id, :bidder_id, :status, :price, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_shift, only: %i[ show edit update destroy ]

  # GET /shifts or /shifts.json
  def index
    @shifts = current_user.shifts
  end

  # GET /shifts/1 or /shifts/1.json
  def show
  end

  # # GET /shifts/new
  # def new
  #   @shift = Shift.new
  # end

  # # GET /shifts/1/edit
  # def edit
  # end

  # # POST /shifts or /shifts.json
  # def create
  #   @shift = Shift.new(shift_params)

  #   respond_to do |format|
  #     if @shift.save
  #       format.html { redirect_to shift_url(@shift), notice: "Shift was successfully created." }
  #       format.json { render :show, status: :created, location: @shift }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @shift.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /shifts/1 or /shifts/1.json
  # def update
  #   respond_to do |format|
  #     if @shift.update(shift_params)
  #       format.html { redirect_to shift_url(@shift), notice: "Shift was successfully updated." }
  #       format.json { render :show, status: :ok, location: @shift }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @shift.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /shifts/1 or /shifts/1.json
  # def destroy
  #   @shift.destroy

  #   respond_to do |format|
  #     format.html { redirect_to shifts_url, notice: "Shift was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shift_params
      params.fetch(:shift, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/auctions/_form.html.slim
.container
  = form_with(model: auction, local: true) do |form|
    - if auction.errors.any?
      #error_explanation
        h2 = pluralize(auction.errors.count, "error") + " prohibited this auction from being saved"

        ul
          - auction.errors.full_messages.each do |message|
            li
              = message
    .price
      p = form.label :price, "prioridad"
      p = form.number_field :price, in: 1..5, step: 1

    .description
      p = form.label :description, "qué ofreces:"
      p = form.text_field :description

    = form.hidden_field  :shift_id, value: @shift.id

    .actions
      .btn = form.submit 'Subastar'

app/views/auctions/edit.html.slim
.container
  h1 Editar subasta

  = render 'form', auction: @auction

  p = link_to 'Ver subasta', @auction 
  p = link_to 'ver otras subastas', auctions_path

app/views/auctions/index.html.slim
.container
  h1 Subastas

  table
    thead
      tr
        th Oferente
        th Fecha
        th colspan="3"
    tbody
      - @auctions.each do |auction|
        tr
          td = auction.bidder.name
          td = auction.date
          td = link_to 'Ver', auction
          td = link_to 'Ofrecer', new_auction_bid_path(auction) unless auction.bidder.id == current_user.id

app/views/auctions/new.html.slim
.container
  h1 Subastando

  = render 'form', auction: @auction

  p = link_to 'Back', auctions_path

app/views/auctions/show.html.slim
.container
  h1 Subasta 

  p 
    span Cuándo  
    strong = @auction.date
  
  - if @auction.bidder == current_user 
    - if @bids.any?
      ul
        - @bids.each do |bid|
          li 
            p oferta de:
            .
              span Quién 
              strong = bid.bidder.name
            .
              span Cuándo 
              strong = bid.date 
            .
              span Pero...  
              span =< bid.description
            
            p = link_to 'Aceptar cambio', bid_accept_path(bid)

    - else
      = link_to 'Ofrecer cambio', new_auction_bid_path(@auction.id)

    / p = link_to 'Aceptar', accept_bid_path(@bid)
    / p = link_to 'Rechazar', decline_bid_path(@bid)


  / p = link_to 'Edit', edit_auction_path(@auction)
  / p = link_to 'Back', auctions_path %>

app/views/bids/_form.html.slim
= form_with(model: bid, local: true) do |form|
  - if bid.errors.any?
    #error_explanation
      h2 = pluralize(bid.errors.count, "error") + " prohibited this bid from being saved:"

      ul
        = bid.errors.full_messages.each do |message|
          li = message


  = form.hidden_field :bidder_id, value: current_user.id 
  = form.hidden_field :auction_id, value: @auction.id
  = form.select :shif_id, options_for_select(@shifts)

  .actions
    = form.submit

app/views/bids/index.html.slim
.container
  h1 Bids

  table
    thead
      tr
        th Cuál pido 
        th Cuál ofrezco
        th A quién
        th Qué ofrece
        th Qué pido
        th colspan="3"


    tbody
      - @bids.each do |bid|
        tr
          td = bid.auction.date
          td = bid.shift.date
          td = bid.auction.bidder.name
          td = bid.auction.description
          td = bid.description
          / td = link_to 'Editar', edit_bid_path(bid)

app/views/bids/new.html.slim
h1 Nueva oferta

= render 'form', bid: @bid 

= link_to 'ver ofertas', bids_path

app/views/home/index.html.slim
.container.m-5
  h1 Home
  - if signed_in?
    p = link_to "Subastas", auctions_path
    p = link_to "Turnos de Chat", shifts_path
    p = link_to "Cerrar sesión", destroy_user_session_path, method: 'delete'
  - else
    p = link_to "Iniciar Sesión", new_user_session_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatMarket</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shifts/index.html.slim
.container
  h1 Turnos de Chat

  table
    thead
      tr
        th Cuándo
        th Quién
        th colspan="2" Acciones

    tbody
      - @shifts.each do |shift|
        tr
          td = shift.date
          td = shift.user.name
          - if shift.user_id == current_user.id
            td = link_to 'Ver  ', shift
            td = link_to 'Subastar  ', new_shift_auction_path(shift_id: shift.id)

app/views/shifts/show.html.slim
p#notice = notice

.container

  p Turno de Chat

  .shifts 
    span Cuándo:  
    strong = @shift.date
  br
  .actions
    p = link_to 'Subastar', new_shift_auction_path(shift_id: @shift.id)

    p = link_to 'Volver', shifts_path